language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.3

services:
  - memcached
  - redis-server

before_install:
  - phpenv config-add ./test/travis/php.ini

install:
  - composer self-update 1.10.22
  - composer install --no-interaction

script:
  - composer cs-check
  - composer license-check
  - composer phpstan
  - composer phpunit-coverage

after_script:
  - composer coveralls

notifications:
  email: false