language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2

before_install:
  - before_script: echo 'extension = redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer install --no-interaction

script:
  - composer cs-check
  - composer license-check
  - composer phpstan
  - composer phpunit-coverage

after_script:
  - composer coveralls

notifications:
  email: false